POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "title",
    "author": "author",
    "url": "www.blogtest.com",
    "likes": "3",
    "userId": "612e58f321e7e1af33b4bb08"
}